name: Manual Build Trigger

on:
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET environment
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      # Install dependencies
      - name: Install dependencies
        run: dotnet restore

      # Build the project
      - name: Build project
        run: dotnet build --configuration Release
